brew "autoconf-archive"
brew "autoconf"
brew "automake"
brew "binutils"
brew "bison"
brew "cmake"
brew "flex"
brew "gcc@14"
brew "glib"
brew "ivykis"
brew "jemalloc"
brew "json-c"
brew "libtool"
brew "openssl@3"
brew "pcre2"
brew "pkgconf"

brew "curl"
brew "gradle"
brew "hiredis"
brew "libdbi"
brew "libmaxminddb"
#brew "libesmtp" - noy yet available in brew
brew "libnet"
brew "libpaho-mqtt"
brew "librdkafka"
brew "net-snmp"
brew "python@3", link: true, force: true
brew "rabbitmq-c"
brew "riemann-client"

# On X86, bottles are outdated; the workflow installs these from source on X64 runners
#brew "mongo-c-driver"
#brew "grpc"
#brew "qpdf"

brew "criterion"

brew "libunwind-headers"
