#!/bin/sh -e

cmd=$1
shift

AM_VERSION=-1.7
INSTALL=${INSTALL:-install}
case "$cmd" in
  get-version)
        head -1 debian/changelog | sed -e 's/.*(\([^)]*\)).*/\1/'
    ;;
  build-exclude-list|dist-exclude-list|prepare-dist)
    ## These lists can be used to delegate build-time and dist-time exclude lists
    ## For example (syslog-ng-agent):
    ##
    echo "out autom4te.cache"
    ##
    ;;
  bootstrap)
    sh autogen.sh
    ;;
  configure)
    ./configure $@
    ;;
  make)
      case $1 in
        install)
            make $@

            . ./dist.conf;
            (echo "VERSION=\"$TECHNICAL_VERSION\""; echo "BROCHURE_VERSION=\"$BROCHURE_VERSION\""; echo "EDITION=pe"; echo "BUILD_ARCH=$ZBS_ARCH"; echo "BUILD_DIST=$ZBS_DIST") > $ZBS_STAGE_DIR/etc/install.dat

            $INSTALL -d -m 755 $ZBS_STAGE_DIR/share/doc
            #Store syslog-ng build options. Has to declare the modulepaths, because
            # syslog-ng doesn't look for them in non-default paths.
            set -e ;
            BUILDOPTS="$ZBS_STAGE_DIR/share/doc/buildopts";
            $ZBS_STAGE_DIR/bin/syslog-ng -V
            $ZBS_STAGE_DIR/bin/syslog-ng -V | sed -n -e '/^Enable/p' -e '/^Available/p' > $BUILDOPTS;
            if test ! -s $BUILDOPTS; then
                echo "Build options file '$BUILDOPTS' has zero size. Please check your filter expression in tgz2build/rules.";
                exit 1;
            fi;

            $INSTALL -d -m 755 $ZBS_STAGE_DIR/share/man
            $INSTALL -d -m 755 $ZBS_STAGE_DIR/share/man/man1
            $INSTALL -d -m 755 $ZBS_STAGE_DIR/share/man/man5
            $INSTALL -d -m 755 $ZBS_STAGE_DIR/share/man/man8
            $INSTALL -m 644 -c AUTHORS $ZBS_STAGE_DIR/share/doc
            $INSTALL -m 644 -c doc/man/pdbtool.1 $ZBS_STAGE_DIR/share/man/man1
            $INSTALL -m 644 -c doc/man/syslog-ng.8 $ZBS_STAGE_DIR/share/man/man8
            $INSTALL -m 644 -c doc/man/syslog-ng.conf.5 $ZBS_STAGE_DIR/share/man/man5
            ;;
        *) make $@ ;;
    esac
    ;;
  *)
    echo "Unknown command: $cmd"
    exit 1
    ;;
esac
exit 0
