#!/bin/sh
mkdir $1/opt/syslog-ng/doc
cp NEWS $1/opt/syslog-ng/doc

mkdir $1/opt/syslog-ng/etc
cp contrib/hpux-packaging/syslog-ng.conf $1/opt/syslog-ng/etc

mkdir $1/sbin
mkdir $1/sbin/init.d
cp contrib/hpux-packaging/syslog-ng.init $1/sbin/init.d/syslog-ng
