/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "riak_dt.pb-c.h"
void   map_field__init
                     (MapField         *message)
{
  static MapField init_value = MAP_FIELD__INIT;
  *message = init_value;
}
size_t map_field__get_packed_size
                     (const MapField *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_field__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t map_field__pack
                     (const MapField *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_field__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t map_field__pack_to_buffer
                     (const MapField *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_field__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MapField *
       map_field__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MapField *)
     protobuf_c_message_unpack (&map_field__descriptor,
                                allocator, len, data);
}
void   map_field__free_unpacked
                     (MapField *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_field__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   map_entry__init
                     (MapEntry         *message)
{
  static MapEntry init_value = MAP_ENTRY__INIT;
  *message = init_value;
}
size_t map_entry__get_packed_size
                     (const MapEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t map_entry__pack
                     (const MapEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t map_entry__pack_to_buffer
                     (const MapEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MapEntry *
       map_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MapEntry *)
     protobuf_c_message_unpack (&map_entry__descriptor,
                                allocator, len, data);
}
void   map_entry__free_unpacked
                     (MapEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt_fetch_req__init
                     (DtFetchReq         *message)
{
  static DtFetchReq init_value = DT_FETCH_REQ__INIT;
  *message = init_value;
}
size_t dt_fetch_req__get_packed_size
                     (const DtFetchReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt_fetch_req__pack
                     (const DtFetchReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt_fetch_req__pack_to_buffer
                     (const DtFetchReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtFetchReq *
       dt_fetch_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtFetchReq *)
     protobuf_c_message_unpack (&dt_fetch_req__descriptor,
                                allocator, len, data);
}
void   dt_fetch_req__free_unpacked
                     (DtFetchReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt_value__init
                     (DtValue         *message)
{
  static DtValue init_value = DT_VALUE__INIT;
  *message = init_value;
}
size_t dt_value__get_packed_size
                     (const DtValue *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt_value__pack
                     (const DtValue *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt_value__pack_to_buffer
                     (const DtValue *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtValue *
       dt_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtValue *)
     protobuf_c_message_unpack (&dt_value__descriptor,
                                allocator, len, data);
}
void   dt_value__free_unpacked
                     (DtValue *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt_fetch_resp__init
                     (DtFetchResp         *message)
{
  static DtFetchResp init_value = DT_FETCH_RESP__INIT;
  *message = init_value;
}
size_t dt_fetch_resp__get_packed_size
                     (const DtFetchResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt_fetch_resp__pack
                     (const DtFetchResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt_fetch_resp__pack_to_buffer
                     (const DtFetchResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtFetchResp *
       dt_fetch_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtFetchResp *)
     protobuf_c_message_unpack (&dt_fetch_resp__descriptor,
                                allocator, len, data);
}
void   dt_fetch_resp__free_unpacked
                     (DtFetchResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_fetch_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   counter_op__init
                     (CounterOp         *message)
{
  static CounterOp init_value = COUNTER_OP__INIT;
  *message = init_value;
}
size_t counter_op__get_packed_size
                     (const CounterOp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &counter_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t counter_op__pack
                     (const CounterOp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &counter_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t counter_op__pack_to_buffer
                     (const CounterOp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &counter_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CounterOp *
       counter_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CounterOp *)
     protobuf_c_message_unpack (&counter_op__descriptor,
                                allocator, len, data);
}
void   counter_op__free_unpacked
                     (CounterOp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &counter_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   set_op__init
                     (SetOp         *message)
{
  static SetOp init_value = SET_OP__INIT;
  *message = init_value;
}
size_t set_op__get_packed_size
                     (const SetOp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t set_op__pack
                     (const SetOp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t set_op__pack_to_buffer
                     (const SetOp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SetOp *
       set_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SetOp *)
     protobuf_c_message_unpack (&set_op__descriptor,
                                allocator, len, data);
}
void   set_op__free_unpacked
                     (SetOp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &set_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   map_update__init
                     (MapUpdate         *message)
{
  static MapUpdate init_value = MAP_UPDATE__INIT;
  *message = init_value;
}
size_t map_update__get_packed_size
                     (const MapUpdate *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t map_update__pack
                     (const MapUpdate *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t map_update__pack_to_buffer
                     (const MapUpdate *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MapUpdate *
       map_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MapUpdate *)
     protobuf_c_message_unpack (&map_update__descriptor,
                                allocator, len, data);
}
void   map_update__free_unpacked
                     (MapUpdate *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   map_op__init
                     (MapOp         *message)
{
  static MapOp init_value = MAP_OP__INIT;
  *message = init_value;
}
size_t map_op__get_packed_size
                     (const MapOp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t map_op__pack
                     (const MapOp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t map_op__pack_to_buffer
                     (const MapOp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MapOp *
       map_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MapOp *)
     protobuf_c_message_unpack (&map_op__descriptor,
                                allocator, len, data);
}
void   map_op__free_unpacked
                     (MapOp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &map_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt_op__init
                     (DtOp         *message)
{
  static DtOp init_value = DT_OP__INIT;
  *message = init_value;
}
size_t dt_op__get_packed_size
                     (const DtOp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt_op__pack
                     (const DtOp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt_op__pack_to_buffer
                     (const DtOp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtOp *
       dt_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtOp *)
     protobuf_c_message_unpack (&dt_op__descriptor,
                                allocator, len, data);
}
void   dt_op__free_unpacked
                     (DtOp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt_update_req__init
                     (DtUpdateReq         *message)
{
  static DtUpdateReq init_value = DT_UPDATE_REQ__INIT;
  *message = init_value;
}
size_t dt_update_req__get_packed_size
                     (const DtUpdateReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt_update_req__pack
                     (const DtUpdateReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt_update_req__pack_to_buffer
                     (const DtUpdateReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtUpdateReq *
       dt_update_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtUpdateReq *)
     protobuf_c_message_unpack (&dt_update_req__descriptor,
                                allocator, len, data);
}
void   dt_update_req__free_unpacked
                     (DtUpdateReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dt_update_resp__init
                     (DtUpdateResp         *message)
{
  static DtUpdateResp init_value = DT_UPDATE_RESP__INIT;
  *message = init_value;
}
size_t dt_update_resp__get_packed_size
                     (const DtUpdateResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dt_update_resp__pack
                     (const DtUpdateResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dt_update_resp__pack_to_buffer
                     (const DtUpdateResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DtUpdateResp *
       dt_update_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DtUpdateResp *)
     protobuf_c_message_unpack (&dt_update_resp__descriptor,
                                allocator, len, data);
}
void   dt_update_resp__free_unpacked
                     (DtUpdateResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &dt_update_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue map_field__map_field_type__enum_values_by_number[5] =
{
  { "COUNTER", "MAP_FIELD__MAP_FIELD_TYPE__COUNTER", 1 },
  { "SET", "MAP_FIELD__MAP_FIELD_TYPE__SET", 2 },
  { "REGISTER", "MAP_FIELD__MAP_FIELD_TYPE__REGISTER", 3 },
  { "FLAG", "MAP_FIELD__MAP_FIELD_TYPE__FLAG", 4 },
  { "MAP", "MAP_FIELD__MAP_FIELD_TYPE__MAP", 5 },
};
static const ProtobufCIntRange map_field__map_field_type__value_ranges[] = {
{1, 0},{0, 5}
};
const ProtobufCEnumValueIndex map_field__map_field_type__enum_values_by_name[5] =
{
  { "COUNTER", 0 },
  { "FLAG", 3 },
  { "MAP", 4 },
  { "REGISTER", 2 },
  { "SET", 1 },
};
const ProtobufCEnumDescriptor map_field__map_field_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "MapField.MapFieldType",
  "MapFieldType",
  "MapField__MapFieldType",
  "",
  5,
  map_field__map_field_type__enum_values_by_number,
  5,
  map_field__map_field_type__enum_values_by_name,
  1,
  map_field__map_field_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor map_field__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapField, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapField, type),
    &map_field__map_field_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned map_field__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange map_field__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor map_field__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MapField",
  "MapField",
  "MapField",
  "",
  sizeof(MapField),
  2,
  map_field__field_descriptors,
  map_field__field_indices_by_name,
  1,  map_field__number_ranges,
  (ProtobufCMessageInit) map_field__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor map_entry__field_descriptors[6] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapEntry, field),
    &map_field__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter_value",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(MapEntry, has_counter_value),
    PROTOBUF_C_OFFSETOF(MapEntry, counter_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_value",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(MapEntry, n_set_value),
    PROTOBUF_C_OFFSETOF(MapEntry, set_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_value",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(MapEntry, has_register_value),
    PROTOBUF_C_OFFSETOF(MapEntry, register_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flag_value",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(MapEntry, has_flag_value),
    PROTOBUF_C_OFFSETOF(MapEntry, flag_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_value",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MapEntry, n_map_value),
    PROTOBUF_C_OFFSETOF(MapEntry, map_value),
    &map_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned map_entry__field_indices_by_name[] = {
  1,   /* field[1] = counter_value */
  0,   /* field[0] = field */
  4,   /* field[4] = flag_value */
  5,   /* field[5] = map_value */
  3,   /* field[3] = register_value */
  2,   /* field[2] = set_value */
};
static const ProtobufCIntRange map_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor map_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MapEntry",
  "MapEntry",
  "MapEntry",
  "",
  sizeof(MapEntry),
  6,
  map_entry__field_descriptors,
  map_entry__field_indices_by_name,
  1,  map_entry__number_ranges,
  (ProtobufCMessageInit) map_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean dt_fetch_req__include_context__default_value = 1;
static const ProtobufCFieldDescriptor dt_fetch_req__field_descriptors[11] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtFetchReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtFetchReq, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtFetchReq, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_r),
    PROTOBUF_C_OFFSETOF(DtFetchReq, r),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pr",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_pr),
    PROTOBUF_C_OFFSETOF(DtFetchReq, pr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "basic_quorum",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_basic_quorum),
    PROTOBUF_C_OFFSETOF(DtFetchReq, basic_quorum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notfound_ok",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_notfound_ok),
    PROTOBUF_C_OFFSETOF(DtFetchReq, notfound_ok),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_timeout),
    PROTOBUF_C_OFFSETOF(DtFetchReq, timeout),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sloppy_quorum",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_sloppy_quorum),
    PROTOBUF_C_OFFSETOF(DtFetchReq, sloppy_quorum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_val",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_n_val),
    PROTOBUF_C_OFFSETOF(DtFetchReq, n_val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "include_context",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtFetchReq, has_include_context),
    PROTOBUF_C_OFFSETOF(DtFetchReq, include_context),
    NULL,
    &dt_fetch_req__include_context__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt_fetch_req__field_indices_by_name[] = {
  5,   /* field[5] = basic_quorum */
  0,   /* field[0] = bucket */
  10,   /* field[10] = include_context */
  1,   /* field[1] = key */
  9,   /* field[9] = n_val */
  6,   /* field[6] = notfound_ok */
  4,   /* field[4] = pr */
  3,   /* field[3] = r */
  8,   /* field[8] = sloppy_quorum */
  7,   /* field[7] = timeout */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange dt_fetch_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor dt_fetch_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DtFetchReq",
  "DtFetchReq",
  "DtFetchReq",
  "",
  sizeof(DtFetchReq),
  11,
  dt_fetch_req__field_descriptors,
  dt_fetch_req__field_indices_by_name,
  1,  dt_fetch_req__number_ranges,
  (ProtobufCMessageInit) dt_fetch_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dt_value__field_descriptors[3] =
{
  {
    "counter_value",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(DtValue, has_counter_value),
    PROTOBUF_C_OFFSETOF(DtValue, counter_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_value",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtValue, n_set_value),
    PROTOBUF_C_OFFSETOF(DtValue, set_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_value",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DtValue, n_map_value),
    PROTOBUF_C_OFFSETOF(DtValue, map_value),
    &map_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt_value__field_indices_by_name[] = {
  0,   /* field[0] = counter_value */
  2,   /* field[2] = map_value */
  1,   /* field[1] = set_value */
};
static const ProtobufCIntRange dt_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dt_value__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DtValue",
  "DtValue",
  "DtValue",
  "",
  sizeof(DtValue),
  3,
  dt_value__field_descriptors,
  dt_value__field_indices_by_name,
  1,  dt_value__number_ranges,
  (ProtobufCMessageInit) dt_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue dt_fetch_resp__data_type__enum_values_by_number[3] =
{
  { "COUNTER", "DT_FETCH_RESP__DATA_TYPE__COUNTER", 1 },
  { "SET", "DT_FETCH_RESP__DATA_TYPE__SET", 2 },
  { "MAP", "DT_FETCH_RESP__DATA_TYPE__MAP", 3 },
};
static const ProtobufCIntRange dt_fetch_resp__data_type__value_ranges[] = {
{1, 0},{0, 3}
};
const ProtobufCEnumValueIndex dt_fetch_resp__data_type__enum_values_by_name[3] =
{
  { "COUNTER", 0 },
  { "MAP", 2 },
  { "SET", 1 },
};
const ProtobufCEnumDescriptor dt_fetch_resp__data_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "DtFetchResp.DataType",
  "DataType",
  "DtFetchResp__DataType",
  "",
  3,
  dt_fetch_resp__data_type__enum_values_by_number,
  3,
  dt_fetch_resp__data_type__enum_values_by_name,
  1,
  dt_fetch_resp__data_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dt_fetch_resp__field_descriptors[3] =
{
  {
    "context",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtFetchResp, has_context),
    PROTOBUF_C_OFFSETOF(DtFetchResp, context),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtFetchResp, type),
    &dt_fetch_resp__data_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtFetchResp, value),
    &dt_value__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt_fetch_resp__field_indices_by_name[] = {
  0,   /* field[0] = context */
  1,   /* field[1] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange dt_fetch_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dt_fetch_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DtFetchResp",
  "DtFetchResp",
  "DtFetchResp",
  "",
  sizeof(DtFetchResp),
  3,
  dt_fetch_resp__field_descriptors,
  dt_fetch_resp__field_indices_by_name,
  1,  dt_fetch_resp__number_ranges,
  (ProtobufCMessageInit) dt_fetch_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor counter_op__field_descriptors[1] =
{
  {
    "increment",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(CounterOp, has_increment),
    PROTOBUF_C_OFFSETOF(CounterOp, increment),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned counter_op__field_indices_by_name[] = {
  0,   /* field[0] = increment */
};
static const ProtobufCIntRange counter_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor counter_op__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "CounterOp",
  "CounterOp",
  "CounterOp",
  "",
  sizeof(CounterOp),
  1,
  counter_op__field_descriptors,
  counter_op__field_indices_by_name,
  1,  counter_op__number_ranges,
  (ProtobufCMessageInit) counter_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor set_op__field_descriptors[2] =
{
  {
    "adds",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(SetOp, n_adds),
    PROTOBUF_C_OFFSETOF(SetOp, adds),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "removes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(SetOp, n_removes),
    PROTOBUF_C_OFFSETOF(SetOp, removes),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned set_op__field_indices_by_name[] = {
  0,   /* field[0] = adds */
  1,   /* field[1] = removes */
};
static const ProtobufCIntRange set_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor set_op__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "SetOp",
  "SetOp",
  "SetOp",
  "",
  sizeof(SetOp),
  2,
  set_op__field_descriptors,
  set_op__field_indices_by_name,
  1,  set_op__number_ranges,
  (ProtobufCMessageInit) set_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue map_update__flag_op__enum_values_by_number[2] =
{
  { "ENABLE", "MAP_UPDATE__FLAG_OP__ENABLE", 1 },
  { "DISABLE", "MAP_UPDATE__FLAG_OP__DISABLE", 2 },
};
static const ProtobufCIntRange map_update__flag_op__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex map_update__flag_op__enum_values_by_name[2] =
{
  { "DISABLE", 1 },
  { "ENABLE", 0 },
};
const ProtobufCEnumDescriptor map_update__flag_op__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "MapUpdate.FlagOp",
  "FlagOp",
  "MapUpdate__FlagOp",
  "",
  2,
  map_update__flag_op__enum_values_by_number,
  2,
  map_update__flag_op__enum_values_by_name,
  1,
  map_update__flag_op__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor map_update__field_descriptors[6] =
{
  {
    "field",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapUpdate, field),
    &map_field__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter_op",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapUpdate, counter_op),
    &counter_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_op",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapUpdate, set_op),
    &set_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "register_op",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(MapUpdate, has_register_op),
    PROTOBUF_C_OFFSETOF(MapUpdate, register_op),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flag_op",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(MapUpdate, has_flag_op),
    PROTOBUF_C_OFFSETOF(MapUpdate, flag_op),
    &map_update__flag_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_op",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(MapUpdate, map_op),
    &map_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned map_update__field_indices_by_name[] = {
  1,   /* field[1] = counter_op */
  0,   /* field[0] = field */
  4,   /* field[4] = flag_op */
  5,   /* field[5] = map_op */
  3,   /* field[3] = register_op */
  2,   /* field[2] = set_op */
};
static const ProtobufCIntRange map_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor map_update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MapUpdate",
  "MapUpdate",
  "MapUpdate",
  "",
  sizeof(MapUpdate),
  6,
  map_update__field_descriptors,
  map_update__field_indices_by_name,
  1,  map_update__number_ranges,
  (ProtobufCMessageInit) map_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor map_op__field_descriptors[2] =
{
  {
    "removes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MapOp, n_removes),
    PROTOBUF_C_OFFSETOF(MapOp, removes),
    &map_field__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "updates",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(MapOp, n_updates),
    PROTOBUF_C_OFFSETOF(MapOp, updates),
    &map_update__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned map_op__field_indices_by_name[] = {
  0,   /* field[0] = removes */
  1,   /* field[1] = updates */
};
static const ProtobufCIntRange map_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor map_op__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "MapOp",
  "MapOp",
  "MapOp",
  "",
  sizeof(MapOp),
  2,
  map_op__field_descriptors,
  map_op__field_indices_by_name,
  1,  map_op__number_ranges,
  (ProtobufCMessageInit) map_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dt_op__field_descriptors[3] =
{
  {
    "counter_op",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtOp, counter_op),
    &counter_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_op",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtOp, set_op),
    &set_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_op",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtOp, map_op),
    &map_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt_op__field_indices_by_name[] = {
  0,   /* field[0] = counter_op */
  2,   /* field[2] = map_op */
  1,   /* field[1] = set_op */
};
static const ProtobufCIntRange dt_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dt_op__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DtOp",
  "DtOp",
  "DtOp",
  "",
  sizeof(DtOp),
  3,
  dt_op__field_descriptors,
  dt_op__field_indices_by_name,
  1,  dt_op__number_ranges,
  (ProtobufCMessageInit) dt_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean dt_update_req__return_body__default_value = 0;
static const protobuf_c_boolean dt_update_req__include_context__default_value = 1;
static const ProtobufCFieldDescriptor dt_update_req__field_descriptors[13] =
{
  {
    "bucket",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtUpdateReq, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_key),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtUpdateReq, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_context),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, context),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DtUpdateReq, op),
    &dt_op__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_w),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, w),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dw",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_dw),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, dw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pw",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_pw),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, pw),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_body",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_return_body),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, return_body),
    NULL,
    &dt_update_req__return_body__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_timeout),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, timeout),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sloppy_quorum",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_sloppy_quorum),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, sloppy_quorum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_val",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_n_val),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, n_val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "include_context",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(DtUpdateReq, has_include_context),
    PROTOBUF_C_OFFSETOF(DtUpdateReq, include_context),
    NULL,
    &dt_update_req__include_context__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt_update_req__field_indices_by_name[] = {
  0,   /* field[0] = bucket */
  3,   /* field[3] = context */
  6,   /* field[6] = dw */
  12,   /* field[12] = include_context */
  1,   /* field[1] = key */
  11,   /* field[11] = n_val */
  4,   /* field[4] = op */
  7,   /* field[7] = pw */
  8,   /* field[8] = return_body */
  10,   /* field[10] = sloppy_quorum */
  9,   /* field[9] = timeout */
  2,   /* field[2] = type */
  5,   /* field[5] = w */
};
static const ProtobufCIntRange dt_update_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor dt_update_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DtUpdateReq",
  "DtUpdateReq",
  "DtUpdateReq",
  "",
  sizeof(DtUpdateReq),
  13,
  dt_update_req__field_descriptors,
  dt_update_req__field_indices_by_name,
  1,  dt_update_req__number_ranges,
  (ProtobufCMessageInit) dt_update_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dt_update_resp__field_descriptors[5] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtUpdateResp, has_key),
    PROTOBUF_C_OFFSETOF(DtUpdateResp, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "context",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtUpdateResp, has_context),
    PROTOBUF_C_OFFSETOF(DtUpdateResp, context),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "counter_value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(DtUpdateResp, has_counter_value),
    PROTOBUF_C_OFFSETOF(DtUpdateResp, counter_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_value",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(DtUpdateResp, n_set_value),
    PROTOBUF_C_OFFSETOF(DtUpdateResp, set_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map_value",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(DtUpdateResp, n_map_value),
    PROTOBUF_C_OFFSETOF(DtUpdateResp, map_value),
    &map_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dt_update_resp__field_indices_by_name[] = {
  1,   /* field[1] = context */
  2,   /* field[2] = counter_value */
  0,   /* field[0] = key */
  4,   /* field[4] = map_value */
  3,   /* field[3] = set_value */
};
static const ProtobufCIntRange dt_update_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dt_update_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DtUpdateResp",
  "DtUpdateResp",
  "DtUpdateResp",
  "",
  sizeof(DtUpdateResp),
  5,
  dt_update_resp__field_descriptors,
  dt_update_resp__field_indices_by_name,
  1,  dt_update_resp__number_ranges,
  (ProtobufCMessageInit) dt_update_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
