#! /usr/bin/dh-exec

etc/syslog-ng/*
usr/bin/*
usr/sbin/*
usr/lib/syslog-ng/libsyslog-ng-*.so.*
usr/lib/syslog-ng/libevtlog-*.so.*
usr/lib/syslog-ng/libsecret-storage.so.*
usr/lib/syslog-ng/*/libsdjournal.so
usr/lib/syslog-ng/*/libaffile.so
usr/lib/syslog-ng/*/libafprog.so
usr/lib/syslog-ng/*/libafsocket.so
usr/lib/syslog-ng/*/libafuser.so
usr/lib/syslog-ng/*/libbasicfuncs.so
usr/lib/syslog-ng/*/libconfgen.so
usr/lib/syslog-ng/*/libcryptofuncs.so
usr/lib/syslog-ng/*/libcsvparser.so
usr/lib/syslog-ng/*/libdbparser.so
usr/lib/syslog-ng/*/libkvformat.so
usr/lib/syslog-ng/*/libtags-parser.so
usr/lib/syslog-ng/*/liblinux-kmsg-format.so
usr/lib/syslog-ng/*/libpseudofile.so
usr/lib/syslog-ng/*/libsyslogformat.so
usr/lib/syslog-ng/*/libsystem-source.so
usr/lib/syslog-ng/*/libdate.so
usr/lib/syslog-ng/*/libcef.so
usr/lib/syslog-ng/*/libdisk-buffer.so
usr/lib/syslog-ng/*/libxml.so
usr/lib/syslog-ng/*/libappmodel.so
usr/lib/syslog-ng/*/libjson-plugin.so
usr/share/syslog-ng/include/scl/system/*
usr/share/syslog-ng/include/scl/syslogconf/*
usr/share/syslog-ng/include/scl/rewrite/*
usr/share/syslog-ng/include/scl/mbox/*
usr/share/syslog-ng/include/scl/apache/*
usr/share/syslog-ng/include/scl/loggly/*
usr/share/syslog-ng/include/scl/logmatic/*
usr/share/syslog-ng/include/scl/solaris/*
usr/share/syslog-ng/include/scl/cisco/*
usr/share/syslog-ng/include/scl/windowseventlog/*
usr/share/syslog-ng/include/scl/loadbalancer/*
usr/share/syslog-ng/include/scl/iptables/*
usr/share/syslog-ng/include/scl/default-network-drivers/*
usr/share/syslog-ng/include/scl/sudo/*
usr/share/syslog-ng/include/scl/nodejs/*
usr/share/syslog-ng/include/scl/osquery/*
usr/share/syslog-ng/include/scl/ewmm/*
usr/share/syslog-ng/include/scl/graylog2/*
usr/share/syslog-ng/xsd/*

#Templates with json dependencies
usr/share/syslog-ng/include/scl/cim/*
[!kfreebsd-any] debian/syslog-ng.systemd =>  lib/systemd/system/syslog-ng.service

debian/syslog-ng.conf                   /etc/syslog-ng/

[kfreebsd-any] debian/tty10.kfreebsd.conf => /usr/share/syslog-ng/include/scl/system/tty10.conf
[!kfreebsd-any] debian/tty10.linux.conf   => /usr/share/syslog-ng/include/scl/system/tty10.conf
