.\"     Title: pdbtool
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/30/2009
.\"    Manual: The pdbtool manual page
.\"    Source: 
.\"
.TH "PDBTOOL" "1" "11/30/2009" "" "The pdbtool manual page"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
pdbtool - An application to test and convert syslog-ng pattern database rules
.SH "SYNOPSIS"
.HP 8
\fBpdbtool\fR [command] [options]
.SH "DESCRIPTION"
.PP
This manual page is only an abstract; for the complete documentation of syslog\-ng and pdbtool, see
\fI \fBThe syslog\-ng Administrator Guide\fR \fR\&[1]\.
.PP
The syslog\-ng application can match the contents of the log messages to a database of predefined message patterns (also called patterndb)\. By comparing the messages to the known patterns, syslog\-ng is able to identify the exact type of the messages, tag the messages, and sort them into message classes\. The message classes can be used to classify the type of the event described in the log message\. The functionality of the pattern database is similar to that of the logcheck project, but the syslog\-ng approach is faster, scales better, and is much easier to maintain compared to the regular expressions of logcheck\.
.PP
The
\fBpdbtool\fR
application is a utility that can be used to:
.sp
.RS 4
\h'-04'\(bu\h'+03'test message patterns;
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'convert an older pattern database to the latest database format;
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'merge pattern databases into a single file;
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'dump the RADIX tree built from the pattern database (or a part of it) to explore how the pattern matching works\.
.RE
.SH "THE MATCH COMMAND"
.HP 6
\fBmatch\fR [options]
.PP
Use the
\fBmatch\fR
command to test the rules in a pattern database\. The command tries to match the specified message against the patterns of the database, evaluates the parsers of the pattern, and also displays which part of the message was parsed successfully\. The command returns with a
\fI0\fR
(success) or
\fI1\fR
(no match) return code and displays the following information:
.sp
.RS 4
\h'-04'\(bu\h'+03'the class assigned to the message (e\.g\., system, violation, etc\.),
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'the ID of the rule that matched the message, and
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'the values of the parsers (if there were parsers in the matching pattern)\.
.RE
.PP
The
\fBmatch\fR
command has the following options:
.PP
\fB\-\-color\-out \fR or \fB\-c\fR
.RS 4
Color the terminal output to highlight the part of the message that was successfully parsed\.
.RE
.PP
\fB\-\-debug\-pattern\fR or \fB\-D\fR
.RS 4
Print debugging information about the pattern matching\.
.RE
.PP
\fB\-\-message\fR or \fB\-M\fR
.RS 4
The text of the log message to match (only the
\fI$MESSAGE\fR
part without the syslog headers)\.
.RE
.PP
\fB\-\-pdb\fR or \fB\-p\fR
.RS 4
Name of the pattern database file to use\.
.RE
.PP
\fB\-\-program\fR or \fB\-P\fR
.RS 4
Name of the program to use, as contained in the
\fI$PROGRAM\fR
part of the syslog message\.
.RE
.PP
Example:
.sp
.RS 4
.nf
pdbtool match \-p patterndb\.xml \-P sshd \-M "Accepted publickey for myuser from 127\.0\.0\.1 port 59357 ssh2"
.fi
.RE
.SH "THE MERGE COMMAND"
.HP 6
\fBmerge\fR [options]
.PP
Use the
\fBmerge\fR
command to combine separate pattern database files into a single file (pattern databases are usually stored in separate files per applications to simplify maintenance)\. If a file uses an older database format, it is automatically updated to the latest format (V3)\. See the
\fI \fBThe syslog\-ng Administrator Guide\fR \fR\&[1]
for details on the different pattern database versions\.
.PP
\fB\-\-directory\fR or \fB\-D\fR
.RS 4
The directory that contains the pattern database XML files to be merged\.
.RE
.PP
\fB\-\-pdb\fR or \fB\-p\fR
.RS 4
Name of the output pattern database file\.
.RE
.PP
Example:
.sp
.RS 4
.nf
pdbtool merge \-\-directory /home/me/mypatterns/  \-\-pdb /var/lib/syslog\-ng/patterndb\.xml
.fi
.RE
.sp

Currently it is not possible to convert a file without merging, so if you only want to convert an older pattern database file to the latest format, you have to copy it into an empty directory\.
.SH "THE DUMP COMMAND"
.HP 5
\fBdump\fR [options]
.PP
Display the RADIX tree built from the patterns\. This shows how are the patterns represented in syslog\-ng and it might also help to track down pattern\-matching problems\. The dump utility can dump the tree used for matching the PROGRAM or the MSG parts\.
.PP
\fB\-\-pdb\fR or \fB\-p\fR
.RS 4
Name of the pattern database file to use\.
.RE
.PP
\fB\-\-program\fR or \fB\-P\fR
.RS 4
Displays the RADIX tree built from the patterns belonging to the
\fI$PROGRAM\fR
application\.
.RE
.PP
\fB\-\-program\-tree\fR or \fB\-T\fR
.RS 4
Display the
\fI$PROGRAM\fR
tree\.
.RE
.PP
Example and sample output:
.sp
.RS 4
.nf
pdbtool dump \-p patterndb\.xml  \-P \'sshd\'
.fi
.RE
.sp

.sp
.RS 4
.nf
\'p\'
   \'assword for\'
     @QSTRING:@
       \'from\'
        @QSTRING:@
          \'port \'
            @NUMBER:@ rule_id=\'fc49054e\-75fd\-11dd\-9bba\-001e6806451b\'
              \' ssh\' rule_id=\'fc55cf86\-75fd\-11dd\-9bba\-001e6806451b\'
                 \'2\' rule_id=\'fc4b7982\-75fd\-11dd\-9bba\-001e6806451b\'
    \'ublickey for\'
      @QSTRING:@
        \'from\'
         @QSTRING:@
           \'port \'
             @NUMBER:@ rule_id=\'fc4d377c\-75fd\-11dd\-9bba\-001e6806451b\'
               \' ssh\' rule_id=\'fc5441ac\-75fd\-11dd\-9bba\-001e6806451b\'
                  \'2\' rule_id=\'fc44a9fe\-75fd\-11dd\-9bba\-001e6806451b\'
              
.fi
.RE
.SH "FILES"
.PP

\fI/opt/syslog\-ng/etc/syslog\-ng/\fR
.PP

\fI/opt/syslog\-ng/etc/syslog\-ng/syslog\-ng\.conf\fR
.SH "SEE ALSO"
.PP

\fI \fBThe syslog\-ng Administrator Guide\fR \fR\&[1]
.PP

\fBsyslog\-ng\.conf\fR(5)
.PP

\fBsyslog\-ng\fR(8)
.PP
If you experience any problems or need help with syslog\-ng, visit the
\fI \fBsyslog\-ng mailing list\fR \fR\&[2]
.PP
For news and notifications about the documentation of syslog\-ng, visit the
\fI\fBBalaBit Documentation Blog\fR\fR\&[3]\.
.SH "AUTHOR"
.PP
This manual page was written by the BalaBit Documentation Team <documentation@balabit\.com>\.
.SH "COPYRIGHT"
.PP
Copyright \(co 2000\-2009 BalaBit IT Security Ltd\. Published under the Creative Commons Attribution\-Noncommercial\-No Derivative Works (by\-nc\-nd) 3\.0 license\. See
\fIhttp://creativecommons\.org/\fR
for details\. The latest version is always available at
\fIhttp://www\.balabit\.com/support/documentation\fR\.
.SH "NOTES"
.IP " 1." 4

          \fBThe syslog-ng Administrator Guide\fR
        
.RS 4
\%http://www.balabit.com/support/documentation/
.RE
.IP " 2." 4

          \fBsyslog-ng mailing list\fR
        
.RS 4
\%https://lists.balabit.hu/mailman/listinfo/syslog-ng
.RE
.IP " 3." 4
\fBBalaBit Documentation Blog\fR
.RS 4
\%http://robert.blogs.balabit.com
.RE
