#! /bin/sh

set -e

if [ "$1" = "install" ]; then
        if [ -f /etc/logrotate.d/syslog-ng.disabled ]; then
                if [ -n "$2" ]; then
                        mv -f /etc/logrotate.d/syslog-ng.disabled /etc/logrotate.d/syslog-ng
                elif [ ! -f /etc/logrotate.d/syslog-ng ]; then
                        mv -f /etc/logrotate.d/syslog-ng.disabled /etc/logrotate.d/syslog-ng
                fi
        fi
fi

#DEBHELPER#

exit 0
