#!/bin/sh

set -e

if [ "$1" = "remove" ]; then
    # disable log rotation on removal
    # main file
    [ -f /etc/logrotate.d/syslog-ng ] && mv -f /etc/logrotate.d/syslog-ng /etc/logrotate.d/syslog-ng.disabled
fi

# remove disabled files on purge or complete overwrite.
if [ "$1" = "purge" -o "$1" = "dissappear" ]; then
    # main file
    [ -f /etc/logrotate.d/syslog-ng.disabled ] && rm -f /etc/logrotate.d/syslog-ng.disabled
fi

#DEBHELPER#

exit 0
