.TH slogencrypt 1 "03 September 2025" 4.9.0 "The slogencrypt manual page"
.SH NAME
.PP
slogencrypt \-\-\- Encrypts existing plain text log files using the {{ site.product.short_name }} secure logging environment.
.SH Synopsis
.PP
.RS
.nf
slogencrypt [options] [arguments]
.fi
.RE
.SH Description
.PP
The \fB\fCslogencrypt\fR utility encrypts plain text log files using an existing secure logging environment. Using this utility, log files obtained from a previous installation of syslog\-ng OSE or another logging system can be transferred to a secure logging environment. The order of the log entries is preserved. Encrypting plain text log files using an existing secure logging environment, requires the current encryption key to be supplied in order to preserve consistency.
.SS Example: a general call sequence
.PP
.RS
.nf
slogencrypt \-k <key file> \-m <MAC file> <new key file> <new MAC file> <plain text log> <output file> [counter]
.fi
.RE
.SH Arguments
.RS
.IP \(bu 2
\fB\fC<new key file>\fR
.PP
The file that containa the new encryption key after successful encryption.
.IP \(bu 2
\fB\fC<new MAC file>\fR
.PP
The file receiving the new message authentication code (MAC) of the secure encrypted destination after encryption. In case an existing file is supplied, new entries are appended.
.IP \(bu 2
\fB\fC<input log file>\fR
.PP
The plain text log file that is encrypted using the secure logging environment.
.IP \(bu 2
\fB\fC<output log file>\fR
.PP
The file that contains the encrypted log entries from the supplied plain text log file after encryption.
.IP \(bu 2
\fB\fCcounter\fR
.PP
The current log entry counter of the secure encrypted destination after encryption. This is required if the log entries to be encrypted are appended to an existing secure encrypted destination
.RE
.SH Options
.RS
.IP \(bu 2
\-\-key\-file or \-k
.PP
The current host key from the system where the encryption is performed.
.IP \(bu 2
\-\-mac\-file or \-m
.PP
The current MAC file from the system where the encryption is performed.
.IP \(bu 2
\-\-help or \-h
.PP
Display a help message.
.RE
.SH Files
.PP
\fB\fC/usr/bin/slogencrypt\fR
.PP
\fB\fC/etc/syslog\-ng.conf\fR
.SH Additional Information
.RS
.IP \(bu 2
The syslog\-ng.conf manual page
.IP \(bu 2
The syslog\-ng OSE manual page
.RE
