#!/bin/bash -e

. /dbld/functions.sh

package_type() {
    case "$1" in
      ubuntu-*|debian-*)
         echo deb
         ;;
      centos-*|almalinux-*|rhel-*|fedora-*)
         echo rpm
         ;;
    esac
}

pkg=$(package_type "${IMAGE_PLATFORM}")
/dbld/${pkg}
