#!/bin/sh
set -x
set -e

OS_PLATFORM=$1
OS_GROUP=$(echo ${OS_PLATFORM} | cut -d"-" -f1)

DBLD_DIR=dbld

[ -f ${DBLD_DIR}/images/${OS_GROUP}.prepare.sh ] && . ${DBLD_DIR}/images/${OS_GROUP}.prepare.sh || true
[ -f ${DBLD_DIR}/images/${OS_PLATFORM}.prepare.sh ] && . ${DBLD_DIR}/images/${OS_PLATFORM}.prepare.sh || true
