#!/bin/bash

echo -e "\n\nWelcome to the syslog-ng developer's shell...\n"

echo -e "You can find the source in /source, you can build the source using:\n"
echo -e "\t\$ cd /build"
echo -e "\t\$ /source/configure"
echo -e "\t\$ make"
echo -e "If configure is not yet available, run dbld/rules bootstrap first or manually execute autogen.sh in the source dir"
cd /source
exec bash
