name: CI @ devshell

on:
  pull_request:
  push:
    branches: [ "develop", "master" ]
  schedule:
    - cron: "00 21 * * *"
  workflow_dispatch:
    inputs:
      use_all:
        description: Should we build for all images?
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read   # actions/checkout
  actions: write   # actions/upload-artifact + inherited by devshell-build.yml
  packages: read   # pull ghcr.io/syslog-ng/dbld-* container images

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # We test building in dbld docker images only that have no binary packages, or docker installations.
        # OS varians that have binary packages or docker installations will be built by the 'Nightly release'
        # NOTE: Keep the image list synced with the dbld-images.yaml !!!
        # --------------------------------------------------------------------
        # Current Build/Test Matrix Coverage
        #
        # image - name        | cmake | autotools | gcc | clang | X86-64 | arm64 | light | func | criterion |
        # --------------------|-------|-----------|-----|-------|--------|-------|-------|------|-----------|
        # almalinux-8         |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # almalinux-10        |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # centos-stream9      |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # centos-stream10     |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # fedora-latest       |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # fedora-rawhide      |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # opensuse-tumbleweed |       |           |     |       |        |       |       |      |           | (TODO: not yet enabled)
        # rocky-9             |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ubuntu-focal        |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ---------------------------------------------------------------------------------------------------
        # debian-bullseye     |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # debian-bookworm     |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # debian-testing      |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # debian-sid          |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ubuntu-jammy        |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ubuntu-noble        |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ubuntu-plucky       |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ubuntu-resolute     |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # rhel-8              |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # rhel-9              |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # rhel-10             |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ---------------------------------------------------------------------------------------------------
        # almalinux-9         |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # debian-trixie       |   x   |           |  x  |   x   |   x    |       |   x   |   x  |     x     |
        # ---------------------------------------------------------------------------------------------------
        # devshell            |   x   |     x     |  x  |   x   |   x    |   x   |   x   |   x  |     x     |
        # devshell (i386)     |   x   |           |  x  |       |   x    |       |   x   |   x  |     x     |
        # ---------------------------------------------------------------------------------------------------
        build-tool: [ autotools, cmake ]
        cc: [ gcc, clang ]
        platform: [ ubuntu-24.04-arm, ubuntu-latest ]
        image:
          - name: almalinux-8
            # grpc/protobuf is presented, but configure cannot find protobuf
            configure_flags: "--disable-sql --disable-grpc --disable-ebpf --with-python=3.9"
            cmake_configure_flags: "-DENABLE_SQL=OFF -DENABLE_GRPC=OFF -DENABLE_EBPF=OFF -DPYTHON_VERSION=3.9"
          - name: almalinux-10
            configure_flags: "--disable-sql --disable-mqtt"
            cmake_configure_flags: "-DENABLE_SQL=OFF -DENABLE_MQTT=OFF"
          - name: centos-stream9
            # grpc is presented, but does not compile
            configure_flags: "--disable-sql --disable-mqtt --disable-grpc"
            cmake_configure_flags: "-DENABLE_SQL=OFF -DENABLE_MQTT=OFF -DENABLE_GRPC=OFF"
          - name: centos-stream10
            configure_flags: "--disable-sql --disable-mqtt"
            cmake_configure_flags: "-DENABLE_SQL=OFF -DENABLE_MQTT=OFF"
          - name: fedora-latest
          - name: fedora-rawhide
          # TODO: We still need to implement install_rpm_build_deps for opensuse
          #- name: opensuse-tumbleweed
          - name: rocky-9
          - name: ubuntu-focal
            # too old ebpf
            configure_flags: "--disable-ebpf"
            cmake_configure_flags: "-DENABLE_EBPF=OFF"
          # --------------------------------------------------------------------
          - name: debian-bullseye
            # too old ebpf
            configure_flags: "--disable-ebpf"
            cmake_configure_flags: "-DENABLE_EBPF=OFF"
          - name: debian-bookworm
          - name: debian-testing
          - name: debian-sid
          - name: ubuntu-jammy
            # too old ebpf
            configure_flags: "--disable-ebpf"
            cmake_configure_flags: "-DENABLE_EBPF=OFF"
          - name: ubuntu-noble
            # no bpftool ?!?
            configure_flags: "--disable-ebpf"
            cmake_configure_flags: "-DENABLE_EBPF=OFF"
          - name: ubuntu-plucky
          - name: ubuntu-resolute
          - name: rhel-8
            configure_flags: "--disable-ebpf --with-python=3.9"
            cmake_configure_flags: "-DENABLE_EBPF=OFF -DPYTHON_VERSION=3.9"
          - name: rhel-9
          - name: rhel-10
          # --------------------------------------------------------------------
          - name: almalinux-9
            # grpc is presented, but does not compile
            configure_flags: "--disable-sql --disable-grpc"
            cmake_configure_flags: "-DENABLE_SQL=OFF -DENABLE_GRPC=OFF"
          - name: debian-trixie
          # --------------------------------------------------------------------
          - name: devshell
            # Now only for devsell we support -Werror, all other none-packaged targets are just best efforts
            configure_flags: "--enable-werror"
            cmake_configure_flags: "-DENABLE_WERROR=ON"
          # --------------------------------------------------------------------
        exclude:
          - platform: ubuntu-24.04-arm
          # Test autotools only in devshell, all other none-packaged targets are just best efforts with autotools, use cmake
          - build-tool: autotools
        include:
          # Add back excluded autotools builds for devshell
          - platform: ubuntu-latest
            image:
              name: devshell
            build-tool: autotools
            cc: gcc
          - platform: ubuntu-latest
            image:
              name: devshell
            build-tool: autotools
            cc: clang
          # Currently testing ARM64 in devshell only
          - platform: ubuntu-24.04-arm
            image:
              name: devshell
              arch_suffix: "-arm64"
            build-tool: autotools
            cc: gcc
          - platform: ubuntu-24.04-arm
            image:
              name: devshell
              arch_suffix: "-arm64"
            build-tool: autotools
            cc: clang
          - platform: ubuntu-24.04-arm
            image:
              name: devshell
              arch_suffix: "-arm64"
            build-tool: cmake
            cc: gcc
          - platform: ubuntu-24.04-arm
            image:
              name: devshell
              arch_suffix: "-arm64"
            build-tool: cmake
            cc: clang
          # Currently testing i386 in devshell only
          # NOTE: We use ubuntu-latest (x86_64) because GitHub has no i386 builder support anymore
          - platform: ubuntu-latest
            image:
              name: devshell
              arch_suffix: "-i386"
              # TODO: jemalloc causes hangs in some kira tests, investigate and fix it, but for now just disable it for i386
              configure_flags: "--disable-jemalloc"
              cmake_configure_flags: "-DENABLE_JEMALLOC=OFF"
            build-tool: cmake
            cc: gcc

    uses: ./.github/workflows/devshell-build.yml
    name: Build @ ${{ matrix.image.name }} on ${{ matrix.platform }}
    with:
      build-tool: ${{ matrix.build-tool }}
      cc: ${{ matrix.cc }}
      platform: ${{ matrix.platform }}
      image-name: ${{ matrix.image.name }}
      image-arch-suffix: ${{ matrix.image.arch_suffix }}
      image-cflags: ${{ matrix.image.cflags }}
      image-configure-flags: ${{ matrix.image.configure_flags }}
      image-cmake-configure-flags: ${{ matrix.image.cmake_configure_flags }}
      run-condition: ${{ matrix.image.name == 'devshell' || github.event_name == 'schedule' }}
      use_all: ${{ inputs.use_all == true || github.event_name == 'schedule' }}

  distcheck:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syslog-ng/dbld-devshell:latest
      options: --security-opt seccomp=unconfined --ulimit core=-1

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v4

      - name: Setup Git safedir
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Set ENV variables
        run: |
          . .github/workflows/gh-tools.sh

          DISTCHECK_CONFIGURE_FLAGS="
            --prefix=${HOME}/install/syslog-ng
            --enable-werror
            --with-ivykis=internal
            --with-jsonc=system
            --enable-tcp-wrapper
            --enable-linux-caps
            --enable-manpages
            --enable-all-modules
            --disable-java
            --disable-java-modules
            --with-python=3
          "

          gh_export DISTCHECK_CONFIGURE_FLAGS

      - name: autogen.sh
        run: ./autogen.sh

      - name: configure
        run: ./configure --disable-all-modules --enable-manpages

      - name: distcheck
        run: |
          . tests/build-log-cflags-propagation.sh
          exec_prop_check "make distcheck -j 3 V=1"

  style-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syslog-ng/dbld-devshell:latest

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v4

      - name: Setup Git safedir
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Prepare
        run: |
          ./autogen.sh
          mkdir build && cd build
          ../configure

      - name: Style check (C)
        id: c-style-check
        run: |
          scripts/style-checker.sh format
          git diff --exit-code > c-style-problems.diff || \
            (cat c-style-problems.diff && git reset --hard HEAD && exit 1)

      - name: Style check (pylib)
        if: always()
        working-directory: ./build
        run: |
          make pymodules-linters || (git reset --hard HEAD && exit 1)

      - name: Style check (Light)
        id: light-style-check
        if: always()
        working-directory: ./build
        shell: bash
        run: |
          make light-linters || \
            (git diff > ../light-style-problems.diff ; git reset --hard HEAD && exit 1)

      - name: "Artifact: c-style-problems"
        uses: actions/upload-artifact@v4
        if: always() && steps.c-style-check.outcome == 'failure'
        with:
          name: c-style-problems
          path: c-style-problems.diff

      - name: "Artifact: light-style-problems"
        uses: actions/upload-artifact@v4
        if: always() && steps.light-style-check.outcome == 'failure'
        with:
          name: light-style-problems
          path: light-style-problems.diff

  copyright-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syslog-ng/dbld-devshell:latest
      env:
        COPYRIGHTVERBOSITY: 1

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v4

      - name: Setup Git safedir
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Copyright check
        run: tests/copyright/check.sh . .

      - name: "Artifact: copyright-run.log"
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: copyright-run.log
          path: copyright-run.log

  commits-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/syslog-ng/dbld-devshell:latest

    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git safedir
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Commits check (Pull request)
        if: github.event_name == 'pull_request'
        run: tests/commits/check.sh origin/${{ github.base_ref }}..HEAD

      - name: Commits check (Push)
        if: github.event_name == 'push'
        run: tests/commits/check.sh
