name: Docker

on:
  workflow_call:
    inputs:
      pkg-type:
        required: true
        type: string  # stable / nightly
      tarball-artifact:
        required: false
        type: string
      snapshot-version:
        required: false
        type: string

env:
  DOCKER_IMAGE_NAME: ghcr.io/axoflow/syslog-ng
  PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7

jobs:
  docker:
    name: Docker
    if: github.repository_owner == 'axoflow'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Download source tarball artifact
        if: inputs.tarball-artifact != ''
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tarball-artifact }}
          path: apkbuild/axoflow/syslog-ng

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (syslog-ng version) for Docker
        if: inputs.pkg-type == 'stable'
        id: stable-tags
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_IMAGE_NAME }}
          tags: type=match,pattern=syslog-ng-(.*),group=1
          sep-tags: ','

      - name: Compose Docker image tags
        id: tags
        run: |
          if [[ '${{ inputs.pkg-type }}' = 'stable' ]]; then
            TAGS='${{ steps.stable-tags.outputs.tags }}'
          elif [[ '${{ inputs.pkg-type }}' = 'nightly' ]]; then
            TAGS="${DOCKER_IMAGE_NAME}:nightly,${DOCKER_IMAGE_NAME}:${{ inputs.snapshot-version }}"
          else
            echo Unexpected input: pkg-type=${{ inputs.pkg-type }}
            false
          fi
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: alpine.dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          build-args: |
            PKG_TYPE=${{ inputs.pkg-type }}
            SNAPSHOT_VERSION=${{ inputs.snapshot-version }}
