name: Recovering secrets

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_SECRET - encrypt/decrypt with openssl - useful for public and public repositories
# MY_OPENSSL_PASSWORD - used to protect secrets
# MY_OPENSSL_ITER - Use a number of iterations on the password to derive the encryption key.
#                   High values increase the time required to brute-force the resulting file.
#                   This option enables the use of PBKDF2 algorithm to derive the key.

on:
  push:
  workflow_dispatch:

jobs:
  openssl:
    name: Recover With GPG
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
          MY_OPENSSL_ITER: ${{ secrets.MY_OPENSSL_ITER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PACKAGE_INDEXER_CONFIG_BASE64: ${{ secrets.PACKAGE_INDEXER_CONFIG_BASE64 }}
          PACKAGE_INDEXER_GPG_KEY_BASE64: ${{ secrets.PACKAGE_INDEXER_GPG_KEY_BASE64 }}
          PACKAGE_INDEXER_GPG_KEY_PASSPHRASE: ${{ secrets.PACKAGE_INDEXER_GPG_KEY_PASSPHRASE }}
          PAT_FOR_ACTIONS: ${{ secrets.PAT_FOR_ACTIONS }}

        run: |
          echo "DOCKERHUB_USERNAME ${DOCKERHUB_USERNAME}" > sec.txt
          echo "DOCKERHUB_PASSWORD ${DOCKERHUB_PASSWORD}" >> sec.txt
          echo "PACKAGE_INDEXER_CONFIG_BASE64 ${PACKAGE_INDEXER_CONFIG_BASE64}" >> sec.txt
          echo "PACKAGE_INDEXER_GPG_KEY_BASE64 ${PACKAGE_INDEXER_GPG_KEY_BASE64}" >> sec.txt
          echo "PACKAGE_INDEXER_GPG_KEY_PASSPHRASE ${PACKAGE_INDEXER_GPG_KEY_PASSPHRASE}" >> sec.txt
          echo "PAT_FOR_ACTIONS ${PAT_FOR_ACTIONS}" >> sec.txt
          echo ${MY_OPENSSL_PASSWORD} > pwd.txt
          chmod 600 pwd.txt sec.txt
          gpg2 --output "pwd.asc" --compress-level 9 --armor --batch --passphrase-file pwd.txt --symmetric sec.txt
          cat pwd.asc
          rm *.txt

      - name: upload as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pwd.asc
          path: pwd.asc
