name: Recovering secrets

# Assumption:
# You've created the following GitHub secrets in your repository:
# MY_CLIENT_SECRET - encrypt/decrypt with openssl - useful for public and public repositories
# MY_OPENSSL_PASSWORD - used to protect secrets
# MY_OPENSSL_ITER - Use a number of iterations on the password to derive the encryption key.
#                   High values increase the time required to brute-force the resulting file.
#                   This option enables the use of PBKDF2 algorithm to derive the key.

on:
  push:
  workflow_dispatch:

jobs:
  openssl:
    name: Recover With OpenSSL
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_OPENSSL_PASSWORD: ${{ secrets.MY_OPENSSL_PASSWORD }}
          MY_OPENSSL_ITER: ${{ secrets.MY_OPENSSL_ITER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PACKAGE_INDEXER_CONFIG_BASE64: ${{ secrets.PACKAGE_INDEXER_CONFIG_BASE64 }}
          PACKAGE_INDEXER_GPG_KEY_BASE64: ${{ secrets.PACKAGE_INDEXER_GPG_KEY_BASE64 }}
          PACKAGE_INDEXER_GPG_KEY_PASSPHRASE: ${{ secrets.PACKAGE_INDEXER_GPG_KEY_PASSPHRASE }}
          PAT_FOR_ACTIONS: ${{ secrets.PAT_FOR_ACTIONS }}

        run: |
          echo "DOCKERHUB_PASSWORD (openssl) = $(echo "${DOCKERHUB_PASSWORD}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
          echo "DOCKERHUB_USERNAME (openssl) = $(echo "${DOCKERHUB_USERNAME}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_USERNAME}")"
          echo "PACKAGE_INDEXER_CONFIG_BASE64 (openssl) = $(echo "${PACKAGE_INDEXER_CONFIG_BASE64}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_USERNAME}")"
          echo "PACKAGE_INDEXER_GPG_KEY_BASE64 (openssl) = $(echo "${PACKAGE_INDEXER_GPG_KEY_BASE64}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_USERNAME}")"
          echo "PACKAGE_INDEXER_GPG_KEY_PASSPHRASE (openssl) = $(echo "${PACKAGE_INDEXER_GPG_KEY_PASSPHRASE}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_USERNAME}")"
          echo "PAT_FOR_ACTIONS (openssl) = $(echo "${PAT_FOR_ACTIONS}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | openssl base64 -d | openssl enc -d -pbkdf2 -iter \$MY_OPENSSL_ITER -aes-256-cbc -k \$MY_OPENSSL_PASSWORD"
